package org.sevenstar.monitor.database.toolkit.jdbc.filter;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public interface ICallableStatementFilter {
	
	public void setParamList(List list);
	public List getParamList();
	public String getSql();
	public void setSql(String sql);
	public ResultSet executeQuery(CallableStatement callableStatement) throws SQLException ;
	
	public int executeUpdate(CallableStatement callableStatement) throws SQLException ;
	public int[] executeBatch(CallableStatement callableStatement) throws SQLException;
	
	public boolean execute(CallableStatement callableStatement) throws SQLException ;
	public boolean execute(CallableStatement callableStatement,String sql) throws SQLException;
	public boolean execute(CallableStatement callableStatement,String sql, int autoGeneratedKeys) throws SQLException;
	public boolean execute(CallableStatement callableStatement,String sql, int[] columnIndexes) throws SQLException;
	public boolean execute(CallableStatement callableStatement,String sql, String[] columnNames) throws SQLException;
	
	public ResultSet executeQuery(CallableStatement callableStatement,String sql) throws SQLException;
	
	public int executeUpdate(CallableStatement callableStatement,String sql) throws SQLException;
	public int executeUpdate(CallableStatement callableStatement,String sql, int autoGeneratedKeys) throws SQLException;
	public int executeUpdate(CallableStatement callableStatement,String sql, int[] columnIndexes) throws SQLException;
	public int executeUpdate(CallableStatement callableStatement,String sql, String[] columnNames) throws SQLException;
	

}
