package org.sevenstar.monitor.database.toolkit.jdbc.filter;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public interface IStatementFilter {
    public boolean execute(Statement statement,String sql) throws SQLException;
    public boolean execute(Statement statement,String sql, int autoGeneratedKeys) throws SQLException;
    public boolean execute(Statement statement,String sql, int[] columnIndexes) throws SQLException;
    public boolean execute(Statement statement,String sql, String[] columnNames) throws SQLException;
    public int[] executeBatch(Statement statement) throws SQLException;
    public ResultSet executeQuery(Statement statement,String sql) throws SQLException;
    public int executeUpdate(Statement statement,String sql) throws SQLException ;
    public int executeUpdate(Statement statement,String sql, int autoGeneratedKeys) throws SQLException;
    public int executeUpdate(Statement statement,String sql, int[] columnIndexes) throws SQLException;
    public int executeUpdate(Statement statement,String sql, String[] columnNames) throws SQLException;
}
