package org.sevenstar.monitor.database.filter.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.sevenstar.monitor.database.context.ClientContext;
import org.sevenstar.monitor.database.context.SQLContext;
import org.sevenstar.monitor.database.toolkit.jdbc.filter.IStatementFilter;

public class StatementFilterImpl implements IStatementFilter {

	private void executeClientContext(Statement statement) throws SQLException{
		statement.execute("insert into test(id,client) values(1,'"+ClientContext.getCurrentContext()+"')" );
	}

	public boolean execute(Statement statement, String sql) throws SQLException {
	//	executeClientContext(statement);
		SQLContext.push(sql);
		return statement.execute(sql);
	}

	public boolean execute(Statement statement, String sql,
			int autoGeneratedKeys) throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return  statement.execute(sql, autoGeneratedKeys);
	}

	public boolean execute(Statement statement, String sql, int[] columnIndexes)
			throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.execute(sql, columnIndexes);
	}

	public boolean execute(Statement statement, String sql, String[] columnNames)
			throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.execute(sql, columnNames);
	}

	public int[] executeBatch(Statement statement) throws SQLException {
		//executeClientContext(statement);
		return statement.executeBatch();
	}

	public ResultSet executeQuery(Statement statement, String sql)
			throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.executeQuery(sql);
	}

	public int executeUpdate(Statement statement, String sql)
			throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.executeUpdate(sql);
	}

	public int executeUpdate(Statement statement, String sql,
			int autoGeneratedKeys) throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.executeUpdate(sql, autoGeneratedKeys);
	}

	public int executeUpdate(Statement statement, String sql,
			int[] columnIndexes) throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
 		return statement.executeUpdate(sql, columnIndexes);
	}

	public int executeUpdate(Statement statement, String sql,
			String[] columnNames) throws SQLException {
		//executeClientContext(statement);
		SQLContext.push(sql);
		return statement.executeUpdate(sql, columnNames);
	}

}
